version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    ignore:
      - dependency-name: react
        update-types:
          - version-update:semver-minor
      - dependency-name: react-dom
        update-types:
          - version-update:semver-minor
      - dependency-name: '@testing-library/react'
        update-types:
          - version-update:semver-minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
